require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ReflectionsController do

  def mock_reflection(stubs={})
    @mock_reflection ||= mock_model(Reflection, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all reflections as @reflections" do
      Reflection.stub(:all) { [mock_reflection] }
      get :index
      assigns(:reflections).should eq([mock_reflection])
    end
  end

  describe "GET show" do
    it "assigns the requested reflection as @reflection" do
      Reflection.stub(:find).with("37") { mock_reflection }
      get :show, :id => "37"
      assigns(:reflection).should be(mock_reflection)
    end
  end

  describe "GET new" do
    it "assigns a new reflection as @reflection" do
      Reflection.stub(:new) { mock_reflection }
      get :new
      assigns(:reflection).should be(mock_reflection)
    end
  end

  describe "GET edit" do
    it "assigns the requested reflection as @reflection" do
      Reflection.stub(:find).with("37") { mock_reflection }
      get :edit, :id => "37"
      assigns(:reflection).should be(mock_reflection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created reflection as @reflection" do
        Reflection.stub(:new).with({'these' => 'params'}) { mock_reflection(:save => true) }
        post :create, :reflection => {'these' => 'params'}
        assigns(:reflection).should be(mock_reflection)
      end

      it "redirects to the created reflection" do
        Reflection.stub(:new) { mock_reflection(:save => true) }
        post :create, :reflection => {}
        response.should redirect_to(reflection_url(mock_reflection))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reflection as @reflection" do
        Reflection.stub(:new).with({'these' => 'params'}) { mock_reflection(:save => false) }
        post :create, :reflection => {'these' => 'params'}
        assigns(:reflection).should be(mock_reflection)
      end

      it "re-renders the 'new' template" do
        Reflection.stub(:new) { mock_reflection(:save => false) }
        post :create, :reflection => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reflection" do
        Reflection.stub(:find).with("37") { mock_reflection }
        mock_reflection.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :reflection => {'these' => 'params'}
      end

      it "assigns the requested reflection as @reflection" do
        Reflection.stub(:find) { mock_reflection(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:reflection).should be(mock_reflection)
      end

      it "redirects to the reflection" do
        Reflection.stub(:find) { mock_reflection(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(reflection_url(mock_reflection))
      end
    end

    describe "with invalid params" do
      it "assigns the reflection as @reflection" do
        Reflection.stub(:find) { mock_reflection(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:reflection).should be(mock_reflection)
      end

      it "re-renders the 'edit' template" do
        Reflection.stub(:find) { mock_reflection(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reflection" do
      Reflection.stub(:find).with("37") { mock_reflection }
      mock_reflection.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the reflections list" do
      Reflection.stub(:find) { mock_reflection }
      delete :destroy, :id => "1"
      response.should redirect_to(reflections_url)
    end
  end

end
